#!/usr/bin/env node
// Single source of truth for cross-platform agent rule files.
//
// The *content* (AGENTS.md, docs/kernels/*, docs/guides/*, resolve-advanced/) is
// platform-neutral. Only the trigger/discovery layer differs per IDE. This script
// emits the thin per-platform shims from ONE manifest so they cannot drift, and
// parses tool/action counts straight from their canonical docs so those numbers
// cannot diverge from their own sources.
//
// Usage:
//   node scripts/agent-rules/generate.mjs           # write/update all outputs
//   node scripts/agent-rules/generate.mjs --check    # exit 1 if any output is stale
//
// The dynamic, every-client layer is the MCP server's per-domain prompts
// (color_grade_workflow / timeline_edit_workflow / conform_workflow /
// delivery_workflow in src/server.py); this script only covers the static,
// repo-file layer that non-MCP-prompt discovery relies on.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const CHECK = process.argv.includes('--check');
const GEN = 'GENERATED by scripts/agent-rules/generate.mjs — edit that, not this file.';

// ── Counts: parsed from their canonical sources (never hand-copied) ────────────
function read(p) {
  return readFileSync(join(ROOT, p), 'utf8');
}
function grab(p, re, label) {
  const m = read(p).match(re);
  if (!m) throw new Error(`generate.mjs: could not parse ${label} from ${p} (pattern ${re})`);
  return m[1];
}
const counts = {
  compound: grab('docs/SKILL.md', /Compound \(default\)[^|]*\|[^|]*\|\s*(\d+)\s*tools/, 'compound tool count'),
  granular: grab('docs/SKILL.md', /Granular \(full\)[^|]*\|[^|]*\|\s*(\d+)\s*tools/, 'granular tool count'),
  kernelActions: grab('docs/kernels/README.md', /\*\*(\d+)\s*actions\*\*/, 'kernel action count'),
  advanced: grab('resolve-advanced/README.md', /##\s*Tools\s*\((\d+)\)/, 'advanced tool count'),
};

// ── Domain manifest (the routing source of truth) ──────────────────────────────
const DOMAINS = [
  {
    id: 'color', skill: 'resolve-color', title: 'Color / Grade', prompt: 'color_grade_workflow',
    when: 'grading, correcting, shot matching, developing looks, or applying/modifying LUTs, CDLs, DRX grades, or copied grades',
    kernel: 'docs/kernels/color-grade-kernel.md', guide: 'docs/guides/color-decision-guide.md',
    live: 'timeline_item_color (grade_boundary_report / safe_set_cdl / safe_apply_drx / grade_version_*), graph, gallery_stills, color_group',
    offline: 'drx (match_to_reference, skin_match, shot_match, grade_transfer, cdl_io, lut_apply, relayout, scope_read, verify_grade, …), project_db',
    rule: 'Frame-first — inspect Resolve-rendered frames before applying any grade/look/LUT/CDL/DRX. Compute offline, apply live. drx generate/merge default to space="ui"; a warnings array means a hue curve rendered FLAT. safe_apply_drx defaults to V1/item0 — pass explicit track/item indices and back up a still first.',
  },
  {
    id: 'edit', skill: 'resolve-edit', title: 'Timeline Edit', prompt: 'timeline_edit_workflow',
    when: 'cutting, trimming, pacing, duplicating/moving clips, copying ranges, building variants, tightening a cut, or generating an editorial changelist',
    kernel: 'docs/kernels/timeline-edit-kernel.md', guide: 'docs/guides/editorial-decision-guide.md',
    live: 'timeline (duplicate_clips/copy_clips/move_clips, copy_range/overwrite_range/lift_range, copy_properties), edit_engine, timeline_item, timeline_markers',
    offline: 'editorial (parse_interchange, turnover_changelist, conform_manifest, marker_roundtrip), drt',
    rule: 'No public razor/split — partial overlaps in lift_range are blocked unless allow_partial_item_delete. Use offline editorial to diff two cuts without opening either. Edits reference existing Media Pool items — never derive source media.',
  },
  {
    id: 'conform', skill: 'resolve-conform', title: 'Conform / Interchange', prompt: 'conform_workflow',
    when: 'importing/relinking editorial, checking a conform against a reference, repairing reversed/retimed subclips, tracing grades across a re-conform, or QCing a conformed timeline',
    kernel: 'docs/kernels/timeline-conform-interchange-kernel.md', guide: null,
    live: 'timeline (probe_timeline_structure, detect_gaps_overlaps, source_range_report, export/import_timeline_checked, detect_missing_media, build_relink_plan), media_pool.safe_relink',
    offline: 'conform (frame-oracle QC, reverse-subclip repair, lineage, per-cut frame QC), color_trace, offline_ref, editorial, drt, project_db',
    rule: 'drt is the only lossless project-native round-trip. XML import via the scripting API goes offline — use import_timeline_checked with media sanitize, then exact-path relink. project_db patches need the project CLOSED + iConfirmProjectClosed + a full quit/relaunch. Relink plans are read-only until executed.',
  },
  {
    id: 'delivery', skill: 'resolve-delivery', title: 'Delivery / Deliverable QC', prompt: 'delivery_workflow',
    when: 'preparing render jobs, validating render settings, QCing a finished render vs spec, building render manifests, expanding texted/textless/stems deliverables, verifying media ingest, or producing a provenance/episode report',
    kernel: 'docs/kernels/render-deliver-kernel.md', guide: null,
    live: 'render (probe_render_matrix, validate_render_settings, safe_set_render_settings, prepare_render_job, safe_quick_export), render_presets',
    offline: 'deliverable (deliverable_qc, loudness_qc, reframe_blanking_check, conform_completeness, render_manifest, expand_deliverable), media (ingest_verify, media_inventory, sync, rename_plan), provenance (grade_provenance, cdl_export, episode_report)',
    rule: 'Deliverable QC is report-only: gate=review, never auto-pass-clear — surface per-field verdicts to a human. QC tools refuse rather than fabricate. deliverable/media QC needs ffmpeg+ffprobe on PATH. Render probes touch only synthetic fixtures.',
  },
  {
    id: 'fusion', skill: 'resolve-fusion', title: 'Fusion Composition', prompt: 'fusion_workflow',
    when: 'building or editing Fusion comps — titles, motion graphics, VFX, merges, masks, trackers',
    kernel: 'docs/kernels/fusion-composition-kernel.md', guide: null,
    live: 'fusion_comp (probe_fusion_comp, safe_add_tool, safe_set_inputs, safe_connect_tools)',
    offline: 'fusion (generate, generate_from_template, list_templates, to_api_calls)',
    rule: 'Author/verify the .comp offline, then apply live (to_api_calls maps onto safe_add_tool -> safe_set_inputs -> safe_connect_tools). Probe first — tool availability and input readability vary by build; bulk mutation needs timeline scope.',
  },
  {
    id: 'audio', skill: 'resolve-audio', title: 'Audio / Fairlight', prompt: 'audio_workflow',
    when: 'setting audio properties, syncing audio, isolating voice, generating subtitles, planning Fairlight tracks/buses, checking loudness, routing buses, or splitting/trimming/converting audio',
    kernel: 'docs/kernels/audio-fairlight-kernel.md', guide: null,
    live: 'timeline (probe_audio_item|track, safe_set_audio_properties, safe_auto_sync_audio, voice_isolation_capabilities, subtitle_generation_probe, fairlight_boundary_report)',
    offline: 'audio_plan (track_plan, analyze_coverage, check_loudness), fairlight (bus routing — patches FLStudioModelBA, no scripting API), audio (split/trim/convert)',
    rule: 'Plan/measure offline, apply live. Bus routing has no scripting API — use fairlight (needs better-sqlite3; project CLOSED + quit/relaunch). audio ops need ffmpeg on PATH and write NEW files to scratch, never over source.',
  },
  {
    id: 'media-pool', skill: 'resolve-media-pool', title: 'Media Pool / Ingest', prompt: 'media_pool_workflow',
    when: 'importing media, building multicam timelines, organizing/relinking clips, normalizing metadata, or verifying/inventorying a card before ingest',
    kernel: 'docs/kernels/media-pool-ingest-kernel.md', guide: 'docs/guides/multicam-setup-guide.md',
    live: 'media_pool (safe_import_media|sequence|folder, organize_clips, normalize_metadata, safe_relink|unlink, set_clip_marks, setup_multicam_timeline)',
    offline: 'media (ingest_verify, media_inventory, sync, relink_manifest, rename_plan, reel_normalize, turnover_package, project_hygiene)',
    rule: 'Verify + inventory the card offline before importing, then import/organize live. media needs ffmpeg+ffprobe. Never rename/derive camera originals (rename_plan refuses them). For footage-content analysis use media-analysis; for deliverable-side media QC use delivery.',
  },
  {
    id: 'media-analysis', skill: 'resolve-media-analysis', title: 'Media Analysis', prompt: 'analyze_media',
    when: 'reading or analyzing source media (technical, visual, or transcription) to inform Resolve actions',
    kernel: 'docs/kernels/README.md', guide: 'docs/guides/media-analysis-guide.md',
    live: 'media_analysis (analyze_file/clip/bin/project, commit_vision, summarize, review_timeline_markers)',
    offline: 'media (ingest_verify, media_inventory, sync) on the advanced server',
    rule: 'Source media is READ-ONLY — never modify/transcode/convert/derive. Do not silently downgrade: keep visuals, transcription, persistence, metadata + Media Pool marker writeback on unless the user opts out. Finish each clip with commit_vision or it stays pending (a failure mode).',
  },
];

// ── Shared body used across every platform (frontmatter differs, body does not) ─
function domainBody(d) {
  const depth = d.guide ? `${d.kernel} + ${d.guide}` : d.kernel;
  return [
    `Resolve ${d.title} work. Apply when: ${d.when}.`,
    ``,
    `Two servers — compute offline, apply live:`,
    `- Live (running Resolve, \`davinci-resolve\`): ${d.live}`,
    `- Offline (.drp/.drt/.drx + DB, no Resolve, \`davinci-resolve-advanced\`): ${d.offline}`,
    `- Key rule: ${d.rule}`,
    ``,
    `Depth: ${depth}. On-demand in any MCP client: the \`/${d.prompt}\` slash prompt. Claude Code skill: \`${d.skill}\`. Never modify/transcode/derive source media (AGENTS.md).`,
  ].join('\n');
}

const repoHygiene = [
  `This is the DaVinci Resolve MCP server: a Python MCP server (${counts.compound} compound tools, ${counts.granular} granular in --full mode) driving Resolve via its scripting API, plus an offline Node "advanced" server (${counts.advanced} tools) that authors .drp/.drt/.drx files and patches the project DB with no Resolve running. Kernel coverage: ${counts.kernelActions} guarded workflow actions.`,
  ``,
  `- Canonical agent brief: AGENTS.md. Operating reference: docs/SKILL.md. Per-action depth: docs/kernels/*. Advanced (offline) catalog: resolve-advanced/README.md.`,
  `- Never modify, transcode, convert, proxy, relink, or create derivatives of source media unless explicitly asked. Analysis output goes to sidecars/scratch/the analysis project root.`,
  `- Do not duplicate version numbers, tool counts, or kernel-action counts into prose — they drift. Reference the docs above.`,
].join('\n');

// ── Emit helpers ───────────────────────────────────────────────────────────────
const results = [];
function emit(relPath, content) {
  const abs = join(ROOT, relPath);
  const want = content.endsWith('\n') ? content : content + '\n';
  const have = existsSync(abs) ? readFileSync(abs, 'utf8') : null;
  if (have === want) { results.push(['ok', relPath]); return; }
  if (CHECK) { results.push(['stale', relPath]); return; }
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, want);
  results.push([have === null ? 'created' : 'updated', relPath]);
}
function emitBlock(relPath, begin, end, block) {
  const abs = join(ROOT, relPath);
  const orig = existsSync(abs) ? readFileSync(abs, 'utf8') : '';
  const section = `${begin}\n${block}\n${end}`;
  let next;
  if (orig.includes(begin) && orig.includes(end)) {
    next = orig.replace(new RegExp(`${begin}[\\s\\S]*?${end}`), section);
  } else {
    next = (orig.trimEnd() + '\n\n' + section + '\n').replace(/^\n+/, '');
  }
  if (orig === next) { results.push(['ok', relPath]); return; }
  if (CHECK) { results.push(['stale', relPath]); return; }
  writeFileSync(abs, next);
  results.push([orig ? 'updated' : 'created', relPath]);
}

// ── 1. AGENTS.md — the universal backstop (Codex, OpenCode, Zed, others) ────────
const agentsBlock = [
  `<!-- ${GEN} -->`,
  `## Domain Routing`,
  ``,
  `Per-domain routers pair the live tools with their offline (advanced-server)`,
  `counterparts. Every domain is available on demand in ANY MCP client as a slash`,
  `prompt (\`/color_grade_workflow\`, \`/timeline_edit_workflow\`, \`/conform_workflow\`,`,
  `\`/delivery_workflow\`, \`/analyze_media\`) and, in Claude Code, as a \`.claude/skills/\``,
  `skill. Full per-action depth lives in \`docs/kernels/\`.`,
  ``,
  ...DOMAINS.map((d) => {
    const depth = d.guide ? `${d.kernel} + ${d.guide}` : d.kernel;
    return `- **${d.title}** (\`/${d.prompt}\`, skill \`${d.skill}\`) — ${d.when}. Live: ${d.live.split(' (')[0]}. Offline: ${d.offline.split(' (')[0]}. Depth: ${depth}.`;
  }),
].join('\n');
emitBlock('AGENTS.md', '<!-- BEGIN GENERATED: domain-routing -->', '<!-- END GENERATED: domain-routing -->', agentsBlock);

// ── 2. Cursor — .cursor/rules/*.mdc (semantic "agent-requested" rules) ──────────
emit(
  '.cursor/rules/resolve-repo.mdc',
  `---\ndescription: DaVinci Resolve MCP repo overview and source-media safety\nalwaysApply: true\n---\n\n<!-- ${GEN} -->\n\n${repoHygiene}\n`,
);
for (const d of DOMAINS) {
  emit(
    `.cursor/rules/${d.skill}.mdc`,
    `---\ndescription: ${d.title} in the DaVinci Resolve MCP — ${d.when}\nalwaysApply: false\n---\n\n<!-- ${GEN} -->\n\n${domainBody(d)}\n`,
  );
}

// ── 3. GitHub Copilot / VS Code — .github/instructions/*.instructions.md ────────
for (const d of DOMAINS) {
  emit(
    `.github/instructions/${d.skill}.instructions.md`,
    `---\napplyTo: '**'\n---\n\n<!-- ${GEN} -->\n\n${domainBody(d)}\n`,
  );
}
emit(
  '.github/copilot-instructions.md',
  [
    `# DaVinci Resolve MCP Server — GitHub Copilot Instructions`,
    ``,
    `<!-- ${GEN} -->`,
    ``,
    repoHygiene,
    ``,
    `## Key files`,
    // Exact phrasing below is asserted by tests/test_doc_tool_counts.py — keep it.
    `- \`src/server.py\` — compound MCP server (${counts.compound} tools); \`src/resolve_mcp_server.py\` — Full server (${counts.granular} tools).`,
    `- \`resolve-advanced/\` — offline Node advanced server (${counts.advanced} tools). \`install.py\` — universal installer.`,
    ``,
    `## Domain routing`,
    `Per-domain guidance lives in \`.github/instructions/resolve-*.instructions.md\` and,`,
    `on demand in any MCP client, as the \`/<domain>_workflow\` slash prompts:`,
    ``,
    ...DOMAINS.map((d) => `- **${d.title}** — ${d.when}. Depth: ${d.guide ? `${d.kernel} + ${d.guide}` : d.kernel}.`),
  ].join('\n') + '\n',
);

// ── 4. Windsurf — .windsurf/rules/*.md + legacy .windsurfrules ──────────────────
for (const d of DOMAINS) {
  emit(`.windsurf/rules/${d.skill}.md`, `<!-- ${GEN} -->\n\n${domainBody(d)}\n`);
}

// ── 5. Combined always-on file (legacy flat + always-on rule dirs) ──────────────
// Cline (.clinerules/), Roo (.roo/rules/), and Continue (.continue/rules/) load
// every file in their rules dir unconditionally (no per-file semantic trigger), so
// the idiomatic shape is ONE compact file carrying repo hygiene + the domain table.
// The legacy flat files (.cursorrules/.windsurfrules) use the same body.
const combined = [
  `# DaVinci Resolve MCP — agent rules`,
  ``,
  `<!-- ${GEN} -->`,
  ``,
  repoHygiene,
  ``,
  `## Domain routing`,
  `On demand in any MCP client via slash prompts; full depth in docs/kernels/*:`,
  ...DOMAINS.map((d) => `- **${d.title}** (/${d.prompt}) — ${d.when}. Depth: ${d.guide ? `${d.kernel} + ${d.guide}` : d.kernel}.`),
].join('\n') + '\n';
emit('.cursorrules', combined);
emit('.windsurfrules', combined);
emit('.clinerules', combined); // Cline: single-file convention (a tracked .clinerules already exists)
emit('.roo/rules/resolve-mcp.md', combined); // Roo Code: rules directory
emit('.continue/rules/resolve-mcp.md', combined); // Continue: rules directory

// ── Report ──────────────────────────────────────────────────────────────────────
const stale = results.filter((r) => r[0] === 'stale');
for (const [status, p] of results) {
  if (status !== 'ok') console.log(`  ${status.padEnd(8)} ${p}`);
}
if (CHECK) {
  if (stale.length) {
    console.error(`\n✗ ${stale.length} agent-rule file(s) are stale. Run: node scripts/agent-rules/generate.mjs`);
    process.exit(1);
  }
  console.log('✓ agent-rule files are in sync with the manifest and canonical counts.');
} else {
  const changed = results.filter((r) => r[0] !== 'ok').length;
  console.log(`\n✓ agent rules generated (${changed} file(s) changed, ${results.length} total). Counts: ${counts.compound} compound / ${counts.granular} granular / ${counts.kernelActions} kernel actions / ${counts.advanced} advanced.`);
}
