"""
Prompt Pack Generator - Creates music and voiceover prompts from video analysis.

Milestone 4 implementation.

Reads candidates.json and generates:
- suno_prompt.md/.json - Music generation prompts for Suno AI
- voiceover_script.md/.json - Voiceover script templates

No API calls, no Resolve modifications. Human-in-the-loop by default.
"""

import json
import logging
from dataclasses import dataclass, field, asdict
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any, Optional, Tuple

logger = logging.getLogger("autonomous.prompt_generator")


# ============================================================================
# Data Classes
# ============================================================================

@dataclass
class SectionTiming:
    """Timing for a music section."""
    name: str  # hook, build, peak, outro
    start_sec: float
    end_sec: float
    duration_sec: float
    description: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class MusicPrompt:
    """Complete music generation prompt pack."""

    # Core prompt
    style: str = "cinematic orchestral"
    mood: str = "epic"
    energy_level: str = "medium"  # low, medium, high

    # Tempo
    bpm_min: int = 90
    bpm_max: int = 120

    # Duration
    duration_sec: float = 60.0

    # Sections
    sections: List[SectionTiming] = field(default_factory=list)

    # Raw prompt for Suno
    suno_prompt: str = ""
    suno_tags: List[str] = field(default_factory=list)

    # Source analysis reference
    analysis_summary: Dict[str, Any] = field(default_factory=dict)

    # Metadata
    generated_at: str = field(default_factory=lambda: datetime.now().isoformat())

    def to_dict(self) -> Dict[str, Any]:
        return {
            "style": self.style,
            "mood": self.mood,
            "energy_level": self.energy_level,
            "bpm_range": {"min": self.bpm_min, "max": self.bpm_max},
            "duration_sec": self.duration_sec,
            "sections": [s.to_dict() for s in self.sections],
            "suno_prompt": self.suno_prompt,
            "suno_tags": self.suno_tags,
            "analysis_summary": self.analysis_summary,
            "generated_at": self.generated_at,
        }

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent)

    def to_markdown(self) -> str:
        """Generate human-readable markdown prompt."""
        lines = [
            "# Suno Music Prompt",
            "",
            f"Generated: {self.generated_at}",
            "",
            "## Quick Copy Prompt",
            "",
            "```",
            self.suno_prompt,
            "```",
            "",
            "## Tags",
            "",
            ", ".join(self.suno_tags) if self.suno_tags else "_No tags_",
            "",
            "## Details",
            "",
            f"- **Style**: {self.style}",
            f"- **Mood**: {self.mood}",
            f"- **Energy**: {self.energy_level}",
            f"- **BPM Range**: {self.bpm_min}-{self.bpm_max}",
            f"- **Target Duration**: {self.duration_sec:.1f}s",
            "",
            "## Section Breakdown",
            "",
        ]

        if self.sections:
            lines.append("| Section | Time | Duration | Notes |")
            lines.append("|---------|------|----------|-------|")
            for section in self.sections:
                lines.append(
                    f"| {section.name.title()} | "
                    f"{section.start_sec:.1f}s - {section.end_sec:.1f}s | "
                    f"{section.duration_sec:.1f}s | "
                    f"{section.description} |"
                )
        else:
            lines.append("_No sections defined_")

        lines.extend([
            "",
            "## Source Analysis",
            "",
            f"- Total clips: {self.analysis_summary.get('total_clips', 'N/A')}",
            f"- Total duration: {self.analysis_summary.get('total_duration_sec', 'N/A')}s",
            f"- Scene count: {self.analysis_summary.get('total_scenes', 'N/A')}",
            f"- Average motion: {self.analysis_summary.get('average_motion_score', 'N/A')}",
            f"- Has audio: {not self.analysis_summary.get('clips_with_audio', 0) == 0}",
            "",
            "---",
            "_Generated by DaVinci Resolve MCP Autonomous Editor_",
        ])

        return "\n".join(lines)


@dataclass
class VoiceoverSection:
    """A section of voiceover script."""
    index: int
    timecode: str  # "00:05"
    start_sec: float
    duration_sec: float
    scene_description: str
    suggested_text: str
    tone: str = "neutral"

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class VoiceoverScript:
    """Complete voiceover script template."""

    # Tone settings
    voice_style: str = "professional narrator"
    pace: str = "measured"  # slow, measured, fast
    tone: str = "informative"  # informative, dramatic, conversational

    # Sections
    sections: List[VoiceoverSection] = field(default_factory=list)

    # Full script
    full_script: str = ""

    # ElevenLabs settings (user-configurable)
    elevenlabs_voice_id: Optional[str] = None  # User selects in ElevenLabs
    elevenlabs_stability: float = 0.5
    elevenlabs_similarity: float = 0.75

    # Source analysis reference
    analysis_summary: Dict[str, Any] = field(default_factory=dict)

    # Metadata
    generated_at: str = field(default_factory=lambda: datetime.now().isoformat())

    def to_dict(self) -> Dict[str, Any]:
        return {
            "voice_style": self.voice_style,
            "pace": self.pace,
            "tone": self.tone,
            "sections": [s.to_dict() for s in self.sections],
            "full_script": self.full_script,
            "elevenlabs_settings": {
                "voice_id": self.elevenlabs_voice_id,
                "stability": self.elevenlabs_stability,
                "similarity_boost": self.elevenlabs_similarity,
            },
            "analysis_summary": self.analysis_summary,
            "generated_at": self.generated_at,
        }

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent)

    def to_markdown(self) -> str:
        """Generate human-readable markdown script."""
        lines = [
            "# Voiceover Script",
            "",
            f"Generated: {self.generated_at}",
            "",
            "## Voice Settings",
            "",
            f"- **Style**: {self.voice_style}",
            f"- **Pace**: {self.pace}",
            f"- **Tone**: {self.tone}",
            "",
            "## Full Script",
            "",
            "```",
            self.full_script if self.full_script else "[Script content goes here]",
            "```",
            "",
            "## Section Breakdown",
            "",
        ]

        if self.sections:
            for section in self.sections:
                lines.extend([
                    f"### [{section.timecode}] Section {section.index + 1}",
                    "",
                    f"**Scene**: {section.scene_description}",
                    "",
                    f"**Suggested text** ({section.tone} tone, ~{section.duration_sec:.1f}s):",
                    "",
                    f"> {section.suggested_text}",
                    "",
                ])
        else:
            lines.append("_No sections defined - add your script content above_")

        lines.extend([
            "",
            "## ElevenLabs Settings",
            "",
            f"- Voice ID: `{self.elevenlabs_voice_id or '[Select your voice in ElevenLabs]'}`",
            f"- Stability: {self.elevenlabs_stability}",
            f"- Similarity Boost: {self.elevenlabs_similarity}",
            "",
            "## Usage Notes",
            "",
            "1. Select a voice in [ElevenLabs Voice Library](https://elevenlabs.io/voice-library)",
            "2. Copy the full script or individual sections",
            "3. Paste into ElevenLabs or your preferred TTS service",
            "4. Adjust timing to match your video edit",
            "",
            "---",
            "_Generated by DaVinci Resolve MCP Autonomous Editor_",
        ])

        return "\n".join(lines)


# ============================================================================
# Prompt Generator
# ============================================================================

class PromptGenerator:
    """
    Generates music and voiceover prompts from video analysis.

    Uses motion scores, scene count, and duration to infer:
    - BPM range for music
    - Section timing (hook/build/peak/outro)
    - Mood and energy level
    """

    # Motion score thresholds for energy classification
    MOTION_LOW = 0.3
    MOTION_HIGH = 0.6

    # BPM ranges by energy
    BPM_RANGES = {
        "low": (60, 90),
        "medium": (90, 120),
        "high": (120, 150),
    }

    # Mood inference based on motion patterns
    MOODS = {
        "low_steady": ("contemplative", "ambient, atmospheric, peaceful"),
        "low_rising": ("hopeful", "uplifting, gentle build, inspiring"),
        "medium_steady": ("cinematic", "orchestral, dramatic, film score"),
        "medium_dynamic": ("epic", "powerful, sweeping, heroic"),
        "high_steady": ("intense", "driving, energetic, action"),
        "high_dynamic": ("explosive", "dramatic peaks, tension, release"),
    }

    def __init__(self, work_dir: Optional[Path] = None):
        self.work_dir = Path(work_dir) if work_dir else Path("work")
        self.prompts_dir = self.work_dir / "prompts"
        self.prompts_dir.mkdir(parents=True, exist_ok=True)

    def load_candidates(self, candidates_path: Optional[Path] = None) -> Dict[str, Any]:
        """Load analysis data from candidates.json."""
        if candidates_path is None:
            candidates_path = self.work_dir / "analysis" / "candidates.json"

        candidates_path = Path(candidates_path)

        if not candidates_path.exists():
            raise FileNotFoundError(f"Candidates file not found: {candidates_path}")

        with open(candidates_path, "r", encoding="utf-8") as f:
            return json.load(f)

    def _analyze_motion_pattern(
        self,
        clips: List[Dict[str, Any]],
    ) -> Tuple[str, float, float, List[float]]:
        """
        Analyze motion pattern across all clips.

        Returns:
            Tuple of (pattern_type, avg_motion, motion_variance, motion_by_position)
        """
        # Collect all motion scores
        all_scores = []
        for clip in clips:
            for scene in clip.get("scenes", []):
                score = scene.get("motion_score")
                if score is not None:
                    all_scores.append(score)

        if not all_scores:
            return "medium_steady", 0.5, 0.0, [0.5]

        avg_motion = sum(all_scores) / len(all_scores)

        # Calculate variance
        variance = sum((s - avg_motion) ** 2 for s in all_scores) / len(all_scores)

        # Divide into quarters for pattern analysis
        quarter_len = max(1, len(all_scores) // 4)
        quarters = []
        for i in range(0, len(all_scores), quarter_len):
            chunk = all_scores[i:i + quarter_len]
            if chunk:
                quarters.append(sum(chunk) / len(chunk))

        # Ensure we have exactly 4 quarters
        while len(quarters) < 4:
            quarters.append(avg_motion)
        quarters = quarters[:4]

        # Determine energy level
        if avg_motion < self.MOTION_LOW:
            energy = "low"
        elif avg_motion > self.MOTION_HIGH:
            energy = "high"
        else:
            energy = "medium"

        # Determine dynamic pattern
        # Rising: later quarters higher than earlier
        # Dynamic: high variance
        is_rising = quarters[2] > quarters[0] and quarters[3] > quarters[1]
        is_dynamic = variance > 0.02

        if is_rising and energy == "low":
            pattern = "low_rising"
        elif is_dynamic:
            pattern = f"{energy}_dynamic"
        else:
            pattern = f"{energy}_steady"

        return pattern, avg_motion, variance, quarters

    def _infer_bpm_range(self, energy_level: str, motion_variance: float) -> Tuple[int, int]:
        """Infer appropriate BPM range from energy and motion."""
        base_min, base_max = self.BPM_RANGES.get(energy_level, (90, 120))

        # Add variability based on motion variance
        # Higher variance = wider BPM range
        variance_factor = min(10, int(motion_variance * 100))

        return base_min - variance_factor, base_max + variance_factor

    def _create_section_timings(
        self,
        total_duration: float,
        motion_quarters: List[float],
    ) -> List[SectionTiming]:
        """
        Create music section timings based on video structure.

        Standard structure:
        - Hook (0-20%): Opening grab
        - Build (20-60%): Rising tension
        - Peak/Drop (60-85%): Main energy
        - Outro (85-100%): Resolution
        """
        sections = []

        # Calculate section boundaries
        hook_end = total_duration * 0.20
        build_end = total_duration * 0.60
        peak_end = total_duration * 0.85

        # Describe each section based on motion
        def motion_desc(score: float) -> str:
            if score < 0.3:
                return "subtle movement"
            elif score < 0.5:
                return "moderate activity"
            elif score < 0.7:
                return "dynamic motion"
            else:
                return "high energy"

        sections.append(SectionTiming(
            name="hook",
            start_sec=0,
            end_sec=hook_end,
            duration_sec=hook_end,
            description=f"Opening - {motion_desc(motion_quarters[0])}",
        ))

        sections.append(SectionTiming(
            name="build",
            start_sec=hook_end,
            end_sec=build_end,
            duration_sec=build_end - hook_end,
            description=f"Building tension - {motion_desc(motion_quarters[1])}",
        ))

        sections.append(SectionTiming(
            name="peak/drop",
            start_sec=build_end,
            end_sec=peak_end,
            duration_sec=peak_end - build_end,
            description=f"Main section - {motion_desc(motion_quarters[2])}",
        ))

        sections.append(SectionTiming(
            name="outro",
            start_sec=peak_end,
            end_sec=total_duration,
            duration_sec=total_duration - peak_end,
            description=f"Resolution - {motion_desc(motion_quarters[3])}",
        ))

        return sections

    def _create_voiceover_sections(
        self,
        clips: List[Dict[str, Any]],
        total_duration: float,
    ) -> List[VoiceoverSection]:
        """
        Create voiceover sections based on scene structure.

        Groups scenes into logical narration blocks.
        """
        sections = []

        # Flatten all scenes with timing info
        all_scenes = []
        for clip in clips:
            for scene in clip.get("scenes", []):
                all_scenes.append({
                    "clip_name": clip.get("clip_name", "Unknown"),
                    "start_sec": scene.get("start_sec", 0),
                    "end_sec": scene.get("end_sec", 0),
                    "duration_sec": scene.get("duration_sec", 0),
                    "motion_score": scene.get("motion_score", 0.5),
                })

        if not all_scenes:
            # Create a single placeholder section
            return [VoiceoverSection(
                index=0,
                timecode="00:00",
                start_sec=0,
                duration_sec=total_duration,
                scene_description="Full video",
                suggested_text="[Your narration here]",
                tone="neutral",
            )]

        # Group scenes into narration blocks (roughly 10-15 seconds each)
        TARGET_BLOCK_DURATION = 12.0

        current_block_start = 0
        current_block_scenes = []
        block_index = 0

        for scene in all_scenes:
            current_block_scenes.append(scene)
            block_duration = scene["end_sec"] - current_block_start

            # Start new block if duration threshold reached
            if block_duration >= TARGET_BLOCK_DURATION:
                # Determine tone from motion
                avg_motion = sum(s.get("motion_score", 0.5) or 0.5 for s in current_block_scenes) / len(current_block_scenes)

                if avg_motion < 0.3:
                    tone = "calm"
                elif avg_motion < 0.5:
                    tone = "neutral"
                elif avg_motion < 0.7:
                    tone = "engaged"
                else:
                    tone = "energetic"

                # Create section
                minutes = int(current_block_start // 60)
                seconds = int(current_block_start % 60)
                timecode = f"{minutes:02d}:{seconds:02d}"

                sections.append(VoiceoverSection(
                    index=block_index,
                    timecode=timecode,
                    start_sec=current_block_start,
                    duration_sec=block_duration,
                    scene_description=f"Scenes from {current_block_scenes[0]['clip_name']}",
                    suggested_text=f"[{tone.title()} narration for {block_duration:.1f}s segment]",
                    tone=tone,
                ))

                # Reset for next block
                block_index += 1
                current_block_start = scene["end_sec"]
                current_block_scenes = []

        # Handle remaining scenes
        if current_block_scenes:
            block_duration = all_scenes[-1]["end_sec"] - current_block_start
            # Only add section if it has meaningful duration (>0.5s)
            if block_duration > 0.5:
                minutes = int(current_block_start // 60)
                seconds = int(current_block_start % 60)
                timecode = f"{minutes:02d}:{seconds:02d}"

                sections.append(VoiceoverSection(
                    index=block_index,
                    timecode=timecode,
                    start_sec=current_block_start,
                    duration_sec=block_duration,
                    scene_description="Closing scenes",
                    suggested_text=f"[Concluding narration for {block_duration:.1f}s]",
                    tone="calm",
                ))

        return sections

    def generate_music_prompt(
        self,
        candidates: Dict[str, Any],
        style_override: Optional[str] = None,
    ) -> MusicPrompt:
        """
        Generate music prompt from video analysis.

        Args:
            candidates: Loaded candidates.json data
            style_override: Optional style to use instead of inferred

        Returns:
            MusicPrompt with all settings
        """
        clips = candidates.get("clips", [])
        summary = candidates.get("summary", {})

        total_duration = summary.get("total_duration_sec", 60.0)

        # Analyze motion pattern
        pattern, avg_motion, variance, quarters = self._analyze_motion_pattern(clips)

        # Get mood and style from pattern
        mood, style_hint = self.MOODS.get(pattern, ("cinematic", "orchestral, dramatic"))

        # Determine energy level
        if avg_motion < self.MOTION_LOW:
            energy = "low"
        elif avg_motion > self.MOTION_HIGH:
            energy = "high"
        else:
            energy = "medium"

        # Get BPM range
        bpm_min, bpm_max = self._infer_bpm_range(energy, variance)

        # Create sections
        sections = self._create_section_timings(total_duration, quarters)

        # Build style string
        style = style_override if style_override else style_hint

        # Generate Suno prompt
        suno_prompt = self._build_suno_prompt(
            style=style,
            mood=mood,
            energy=energy,
            bpm_min=bpm_min,
            bpm_max=bpm_max,
            duration=total_duration,
            sections=sections,
        )

        # Generate tags
        suno_tags = self._generate_suno_tags(style, mood, energy)

        return MusicPrompt(
            style=style,
            mood=mood,
            energy_level=energy,
            bpm_min=bpm_min,
            bpm_max=bpm_max,
            duration_sec=total_duration,
            sections=sections,
            suno_prompt=suno_prompt,
            suno_tags=suno_tags,
            analysis_summary=summary,
        )

    def _build_suno_prompt(
        self,
        style: str,
        mood: str,
        energy: str,
        bpm_min: int,
        bpm_max: int,
        duration: float,
        sections: List[SectionTiming],
    ) -> str:
        """Build the actual Suno prompt text."""

        # Core description
        prompt_parts = [
            f"{mood.title()} {style} instrumental track.",
        ]

        # Energy and tempo
        energy_desc = {
            "low": "Slow, contemplative pace",
            "medium": "Moderate, cinematic tempo",
            "high": "Driving, energetic rhythm",
        }
        prompt_parts.append(f"{energy_desc.get(energy, 'Moderate tempo')} around {bpm_min}-{bpm_max} BPM.")

        # Structure hints
        if sections:
            prompt_parts.append(
                f"Structure: Opens gently, builds through middle section, "
                f"peaks with full instrumentation, resolves softly."
            )

        # No vocals
        prompt_parts.append("Instrumental only, no vocals.")

        return " ".join(prompt_parts)

    def _generate_suno_tags(self, style: str, mood: str, energy: str) -> List[str]:
        """Generate Suno-compatible tags."""
        tags = [
            "instrumental",
            mood,
        ]

        # Add style-based tags
        style_lower = style.lower()
        if "orchestral" in style_lower:
            tags.extend(["orchestral", "cinematic"])
        if "ambient" in style_lower:
            tags.extend(["ambient", "atmospheric"])
        if "electronic" in style_lower:
            tags.extend(["electronic", "synth"])
        if "epic" in style_lower:
            tags.append("epic")

        # Energy tags
        energy_tags = {
            "low": ["peaceful", "calm"],
            "medium": ["dramatic", "emotional"],
            "high": ["intense", "powerful"],
        }
        tags.extend(energy_tags.get(energy, []))

        # Deduplicate while preserving order
        seen = set()
        unique_tags = []
        for tag in tags:
            if tag not in seen:
                seen.add(tag)
                unique_tags.append(tag)

        return unique_tags

    def generate_voiceover_script(
        self,
        candidates: Dict[str, Any],
        voice_style: Optional[str] = None,
    ) -> VoiceoverScript:
        """
        Generate voiceover script template from video analysis.

        Args:
            candidates: Loaded candidates.json data
            voice_style: Optional voice style override

        Returns:
            VoiceoverScript with sections and placeholders
        """
        clips = candidates.get("clips", [])
        summary = candidates.get("summary", {})

        total_duration = summary.get("total_duration_sec", 60.0)

        # Analyze motion for pacing
        pattern, avg_motion, variance, _ = self._analyze_motion_pattern(clips)

        # Determine pace from motion
        if avg_motion < 0.3:
            pace = "slow"
            tone = "contemplative"
        elif avg_motion < 0.5:
            pace = "measured"
            tone = "informative"
        elif avg_motion < 0.7:
            pace = "measured"
            tone = "dramatic"
        else:
            pace = "fast"
            tone = "energetic"

        # Create sections
        sections = self._create_voiceover_sections(clips, total_duration)

        # Build full script template
        full_script = self._build_script_template(sections, tone)

        return VoiceoverScript(
            voice_style=voice_style or "professional narrator",
            pace=pace,
            tone=tone,
            sections=sections,
            full_script=full_script,
            analysis_summary=summary,
        )

    def _build_script_template(
        self,
        sections: List[VoiceoverSection],
        overall_tone: str,
    ) -> str:
        """Build a full script template with placeholders."""

        if not sections:
            return "[Your voiceover script here]"

        lines = []

        for section in sections:
            lines.append(f"[{section.timecode}]")
            lines.append(section.suggested_text)
            lines.append("")

        return "\n".join(lines).strip()

    def generate_all(
        self,
        candidates_path: Optional[Path] = None,
    ) -> Tuple[MusicPrompt, VoiceoverScript]:
        """
        Generate both music and voiceover prompts.

        Args:
            candidates_path: Path to candidates.json

        Returns:
            Tuple of (MusicPrompt, VoiceoverScript)
        """
        candidates = self.load_candidates(candidates_path)

        music_prompt = self.generate_music_prompt(candidates)
        voiceover_script = self.generate_voiceover_script(candidates)

        return music_prompt, voiceover_script

    def save_prompts(
        self,
        music_prompt: MusicPrompt,
        voiceover_script: VoiceoverScript,
        output_dir: Optional[Path] = None,
    ) -> Dict[str, Path]:
        """
        Save prompts to files.

        Returns:
            Dict mapping output type to file path
        """
        output_dir = Path(output_dir) if output_dir else self.prompts_dir
        output_dir.mkdir(parents=True, exist_ok=True)

        paths = {}

        # Save music prompt
        suno_md_path = output_dir / "suno_prompt.md"
        suno_json_path = output_dir / "suno_prompt.json"

        with open(suno_md_path, "w", encoding="utf-8") as f:
            f.write(music_prompt.to_markdown())
        paths["suno_md"] = suno_md_path

        with open(suno_json_path, "w", encoding="utf-8") as f:
            f.write(music_prompt.to_json())
        paths["suno_json"] = suno_json_path

        # Save voiceover script
        vo_md_path = output_dir / "voiceover_script.md"
        vo_json_path = output_dir / "voiceover_script.json"

        with open(vo_md_path, "w", encoding="utf-8") as f:
            f.write(voiceover_script.to_markdown())
        paths["voiceover_md"] = vo_md_path

        with open(vo_json_path, "w", encoding="utf-8") as f:
            f.write(voiceover_script.to_json())
        paths["voiceover_json"] = vo_json_path

        logger.info(f"Saved prompts to: {output_dir}")

        return paths


# ============================================================================
# Convenience function
# ============================================================================

def generate_prompt_packs(
    candidates_path: Path,
    output_dir: Optional[Path] = None,
    style_override: Optional[str] = None,
) -> Dict[str, Path]:
    """
    Convenience function to generate all prompt packs.

    Args:
        candidates_path: Path to candidates.json
        output_dir: Output directory (default: work/prompts)
        style_override: Optional music style override

    Returns:
        Dict mapping output type to file path
    """
    generator = PromptGenerator(
        work_dir=candidates_path.parent.parent if candidates_path else None
    )

    candidates = generator.load_candidates(candidates_path)

    music_prompt = generator.generate_music_prompt(candidates, style_override)
    voiceover_script = generator.generate_voiceover_script(candidates)

    return generator.save_prompts(music_prompt, voiceover_script, output_dir)
