"""Behaviorally-verified facts about the DaVinci Resolve scripting API.

The Resolve scripting API is under-documented and frequently behaves differently
from its apparent signature: methods live on objects you wouldn't expect, return
values lie, string keys are silently rejected, and some documented-looking calls
don't exist. This module records facts we have *verified against live Resolve* so
agents and code can look the reality up instead of rediscovering it the hard way.

Each entry is a small dict. Grow it opportunistically — every readback recipe and
every fix that uncovers a surprising behavior should add an entry. Facts are
stamped with the Resolve build they were verified on so drift is visible when a
new version ships.

Optional keys on an entry feed the Blackmagic-facing limitations report
(``docs/reference/api-limitations.md``, generated by
``scripts/gen_api_limitations.py``):

  - ``submit``: ``"missing"`` (a capability Blackmagic should add) or ``"bug"``
    (a behavior Blackmagic should fix). Entries without ``submit`` are internal
    quirks/tips and stay out of the report.
  - ``issue``: GitHub issue number (int) that drove the finding, for cross-ref.

When you add or change a ``submit``-tagged entry, regenerate the report
(``venv/bin/python scripts/gen_api_limitations.py``) or the
``tests.test_api_limitations_doc`` drift guard fails.
"""
from typing import Any, Dict, List, Optional

VERIFIED_ON = "DaVinci Resolve Studio 21.0.0"

# Each entry: symbol, object, reality, recommended, tags. `signature` optional.
API_TRUTH: List[Dict[str, Any]] = [
    {
        "symbol": "MediaPool.AutoSyncAudio",
        "object": "MediaPool",
        "signature": "(clips, settings) -> bool",
        "reality": "The boolean return does not reflect whether clips actually "
                   "linked, and string enum keys in `settings` are silently "
                   "rejected (the call returns False).",
        "recommended": "Resolve the AUDIO_SYNC_* enum constants via the live "
                       "resolve handle, and verify by reading each clip's "
                       "'Synced Audio' property (see verify_by_readback).",
        "tags": ["unreliable-return", "silent-failure", "audio", "enum"],
        "submit": "bug",
        "mitigation": ["_normalize_auto_sync_settings", "_safe_auto_sync_audio"],
    },
    {
        "symbol": "Timeline.CreateSubtitlesFromAudio",
        "object": "Timeline",
        "signature": "(autoCaptionSettings) -> bool",
        "reality": "Same failure mode as AutoSyncAudio: the autoCaptionSettings "
                   "dict is keyed by resolve.SUBTITLE_* enum constants with "
                   "resolve.AUTO_CAPTION_* enum values, so plain string keys like "
                   "{'language': 'korean'} are silently rejected (returns False, "
                   "no subtitle track created). The boolean is also unreliable.",
        "recommended": "Resolve the SUBTITLE_*/AUTO_CAPTION_* constants via the "
                       "live resolve handle (server._normalize_auto_caption_settings) "
                       "and verify by reading the timeline's subtitle track count "
                       "before/after (server._safe_create_subtitles).",
        "tags": ["unreliable-return", "silent-failure", "subtitle", "enum"],
        "submit": "bug",
        "mitigation": ["_normalize_auto_caption_settings", "_safe_create_subtitles"],
    },
    {
        "symbol": "ProjectManager CloudProject family (Create/Load/Import/RestoreCloudProject)",
        "object": "ProjectManager",
        "signature": "(..., cloudSettings) -> Project | bool",
        "reality": "All four take an enum-keyed {cloudSettings} dict "
                   "(resolve.CLOUD_SETTING_* keys, resolve.CLOUD_SYNC_* sync-mode "
                   "values). Plain string keys are silently rejected, so a settings "
                   "dict built from human-readable keys yields no project / False.",
        "recommended": "Resolve the CLOUD_SETTING_*/CLOUD_SYNC_* constants via the "
                       "live resolve handle (server._normalize_cloud_settings) "
                       "before calling, and treat the bool return from "
                       "Import/RestoreCloudProject as advisory.",
        "tags": ["silent-failure", "project", "cloud", "enum"],
        "submit": "bug",
        "mitigation": ["_normalize_cloud_settings"],
    },
    {
        "symbol": "Timeline.Export",
        "object": "Timeline",
        "signature": "(fileName, exportType, exportSubtype) -> bool",
        "reality": "exportType/exportSubtype must be resolve.EXPORT_* enum *values* "
                   "resolved from the live handle. A JSON/MCP caller cannot pass a "
                   "live enum, and a plain string ('fcpxml', or even the constant "
                   "name 'EXPORT_FCPXML_1_10') is silently rejected with no file "
                   "written.",
        "recommended": "Map a friendly format/subtype to the EXPORT_* constant and "
                       "resolve it against the live handle "
                       "(server._timeline_export_spec) before calling; verify the "
                       "output file exists afterward.",
        "tags": ["silent-failure", "timeline", "export", "enum"],
        "submit": "bug",
        "mitigation": ["_timeline_export_spec", "_timeline_export_value"],
    },
    {
        "symbol": "ProjectManager.DeleteProject",
        "object": "ProjectManager",
        "signature": "(projectName) -> bool",
        "reality": "Returns False (no deletion) when the target project is, or "
                   "recently was, the current project, and is flaky on the first "
                   "attempt — so a single bool() call leaves the project undeleted "
                   "with no useful error. CloseProject reliably releases it: a "
                   "delete that had failed six times in a row, a second apart, "
                   "succeeded on the first attempt after one. Switching away with "
                   "LoadProject is NOT reliable — it left the delete failing "
                   "permanently after a heavily-used project, yet succeeded for a "
                   "project that had only been created and loaded. Whatever "
                   "distinguishes the two (modification? an open timeline?) is "
                   "not established, so LoadProject-away cannot be depended on.",
        "recommended": "CloseProject the target FIRST (that is what releases it), "
                       "then LoadProject some named project so the session is not "
                       "left on the unsaveable 'Untitled Project' fallback, then "
                       "delete. Use src/utils/project_cleanup.py:delete_project_safely, "
                       "which does exactly that.",
        "tags": ["unreliable-return", "project", "flaky", "session-lock"],
        "submit": "bug",
    },
    {
        "symbol": "Project.SetSetting('timelinePlaybackFrameRate')",
        "object": "Project",
        "reality": "Returns False for every value form tried (string, int, "
                   "float), both before and after a timeline exists, so the "
                   "playback frame rate cannot be set from the API at all. "
                   "Reported by a community contributor against Resolve Studio "
                   "while assembling a vertical timeline (PR #99).",
        "recommended": "Ask the user to set it in Project Settings > Master "
                       "Settings > Playback frame rate as a SETUP step, before "
                       "any timeline exists. Read it back to confirm; do not "
                       "report it as set on the strength of the call alone.",
        "tags": ["project-settings", "silent-failure", "timeline"],
        "submit": "missing",
    },
    {
        "symbol": "ProjectManager.GetCurrentDatabase",
        "object": "ProjectManager",
        "signature": "() -> {DbType, DbName}",
        "reality": "Returns None when Resolve has come up without attaching to a "
                   "project database — a state it reaches after an unclean "
                   "shutdown, and does not recover from on its own. In that state "
                   "the application looks entirely healthy: it accepts scripting "
                   "connections, and GetProductName, GetVersionString, "
                   "GetCurrentPage and GetCurrentProject all answer normally. But "
                   "CreateProject and LoadProject return False indefinitely, "
                   "SaveProject returns None, and some calls block forever in "
                   "the scripting transport rather than returning at all. "
                   "Observed headless on Studio 19.1.3.7 after force-killing a "
                   "wedged instance; the replacement took 2m05s to become "
                   "scriptable and came up with no database.",
        "recommended": "Treat a non-None GetCurrentDatabase() as the liveness "
                       "check, not a successful connection — every cheaper check "
                       "passes in the wedged state. `resolve_control "
                       "runtime_mode` reports `database_attached` for exactly "
                       "this. There is no repair: quit and restart Resolve.",
        "tags": ["project", "database", "headless", "silent-failure", "startup"],
        "mitigation": ["runtime_mode"],
        "submit": "bug",
    },
    {
        "symbol": "MediaPool.ImportTimelineFromFile",
        "object": "MediaPool",
        "signature": "(filePath, {importOptions}) -> Timeline",
        "reality": "Returns None — no error, no exception — when the requested "
                   "`timelineName` already exists. Measured: importing one file "
                   "three times with the same name succeeded once and returned "
                   "None twice. An iterative loop that reuses a fixed name "
                   "therefore works exactly once and then silently does nothing. "
                   "DRT ignores importOptions entirely (timelineName, "
                   "importSourceClips and sourceClipsFolders are all invalid for "
                   "it): the timeline is named after the FILE, repeats "
                   "auto-uniquify ('iter', 'iter 2', 'iter 3'), and because "
                   "importSourceClips cannot be disabled each DRT import adds "
                   "another copy of the source media to the pool. OTIO is the one "
                   "format that will NOT relink from the pool — with "
                   "importSourceClips=False its timeline rebuilds with correct "
                   "structure and every item OFFLINE, in both GUI and headless.",
        "recommended": "For a repeatable loop use FCP7 XML or AAF with a UNIQUE "
                       "timelineName per iteration plus importSourceClips=False "
                       "and sourceClipsFolders=[root] — verified frame-exact over "
                       "five consecutive imports with no media duplicated. Use DRT "
                       "for one-shot hand-offs only. For OTIO, pass "
                       "importSourceClips=True with a sourceClipsPath. See "
                       "docs/guides/headless-edit-loop.md.",
        "tags": ["timeline", "import", "interchange", "silent-failure", "conform"],
        "submit": "bug",
    },
    {
        "symbol": "Timeline.Export / ImportTimelineFromFile (format fidelity)",
        "object": "Timeline",
        "reality": "The formats are NOT interchangeable, and which one is right "
                   "depends on the job — measured identically in GUI and "
                   "headless. On a rich cut (2 video tracks, audio, per-item "
                   "transform, colours, flags, item and timeline markers) only "
                   "DRT kept everything. FCP7 XML kept the cut, tracks and most "
                   "of the transform, losing only FlipX. AAF kept the cut and "
                   "tracks but RESET THE WHOLE TRANSFORM to defaults. FCPXML 1.10 "
                   "silently dropped an audio track (2v2a in, 2v1a out). OTIO "
                   "lost the source association. EDL collapsed to 1v1a. "
                   "But with media MOVED and sourceClipsPath given, the ranking "
                   "inverts: FCP7 XML, AAF and FCPXML 1.10 relinked 3/3 and stayed "
                   "frame-exact, while DRT relinked 0/3 (sourceClipsPath is not "
                   "valid for DRT, so it cannot be told where the media went), EDL "
                   "relinked 0/3, and OTIO's import returned None outright.",
        "recommended": "Pick per job: DRT for full fidelity with media in place; "
                       "FCP7 XML or AAF for an iterative loop or any conform where "
                       "media may move; never DRT/OTIO/EDL for a relink. Note the "
                       "cut stays frame-exact even when relinking fails, so a "
                       "failed relink leaves a correct offline timeline rather "
                       "than a wrong one. See docs/guides/headless-edit-loop.md.",
        "tags": ["timeline", "export", "import", "interchange", "conform"],
    },
    {
        "symbol": "BMD_RESOLVE_*_DIR environment variables",
        "object": "Resolve",
        "reality": "BMD_RESOLVE_CONFIG_DIR / SUPPORT_DIR / LUT_DIR genuinely "
                   "isolate an instance — a launch with them set builds a private "
                   "config.dat plus its own Resolve Project Library, Fairlight, "
                   "DolbyVision and easyDCP trees, and the resulting instance sees "
                   "ZERO of the machine's real projects. They do NOT defeat the "
                   "single-instance guard: started while another Resolve was "
                   "running, the second process created its private tree and then "
                   "exited silently, logging nothing. So isolated instances are "
                   "possible and PARALLEL instances are not. A fresh config also "
                   "omits `System.Scripting.Mode = 1`, so an isolated instance is "
                   "unreachable by scripting until that line is appended to its "
                   "config.dat (plain ASCII) — until then it runs, opens no "
                   "listener, and looks exactly like a hang. "
                   "BMD_RESOLVE_LOGS_DIR only partly takes: LogArchive/ and "
                   "gpudetect.bin appear there, the main log does not.",
        "recommended": "Use for a CI/render worker that must not see or lock the "
                       "operator's projects. Seed the scripting preference after "
                       "the first boot. Do not expect to run two at once. Recipe "
                       "in docs/reference/headless-cli.md.",
        "tags": ["headless", "isolation", "singleton", "ci", "startup"],
    },
    {
        "symbol": "Resolve -fastmode",
        "object": "Resolve",
        "reality": "Starts a process that stays alive at 0% CPU and never opens "
                   "the scripting listener — port 15000 is not bound at all, and "
                   "it was still unreachable after two minutes. Exercised in an "
                   "isolated sandbox on Studio 19.1.3.7.",
        "recommended": "Not usable for automation; do not pass it. (`-activate` "
                       "and `-deactivate` remain deliberately unexercised: their "
                       "adjacent strings show they mutate this machine's Studio "
                       "licence activation.)",
        "tags": ["headless", "cli-flags"],
    },
    {
        "symbol": "Timeline.Export(EXPORT_FCPXML_1_10)",
        "object": "Timeline",
        "signature": "(fileName, EXPORT_FCPXML_1_10, EXPORT_NONE) -> bool",
        "reality": "Returns True and creates a BUNDLE DIRECTORY at the given "
                   "path containing `Info.fcpxml`, rather than a file — the "
                   "`.fcpxmld` shape Final Cut uses. Two consequences bite "
                   "immediately: a `stat().st_size` check reads the directory "
                   "inode (96 bytes here) and concludes the export is empty, and "
                   "ImportTimelineFromFile on that path fails because it is a "
                   "directory. Every other EXPORT_* type in this build writes a "
                   "plain file, so code that treats them uniformly gets this one "
                   "wrong. Pointed at the inner member, the format round-trips "
                   "frame-exactly in both modes.",
        "recommended": "After exporting, check `Path(p).is_dir()` and import "
                       "`next(Path(p).glob('*.fcpxml'))` instead. Do not size-"
                       "check the export path itself.",
        "tags": ["timeline", "export", "interchange", "fcpxml", "silent-failure"],
        "submit": "bug",
    },
    {
        "symbol": "MediaPool.CreateTimelineFromClips",
        "object": "MediaPool",
        "reality": "Fails with a bare 'Failed to create timeline from clip_infos' "
                   "— naming nothing actionable — when the Media Pool's CURRENT "
                   "folder is not the folder holding the clips, even though every "
                   "clip_id passed is valid and resolvable. Reported against "
                   "Resolve Studio in PR #99.",
        "recommended": "Call MediaPool.SetCurrentFolder() to the clips' bin "
                       "before creating the timeline (media_pool "
                       "set_current_folder). Valid ids are not sufficient.",
        "tags": ["media-pool", "timeline", "unhelpful-error"],
        "submit": "bug",
    },
    {
        "symbol": "TimelineItem.AddFusionComp / LoadFusionCompByName",
        "object": "TimelineItem (media-backed clip)",
        "reality": "A Fusion composition created on a media clip through the API "
                   "is never applied at render. AddFusionComp() returns the comp, "
                   "AddTool/Connect/SetInput all succeed, and the whole graph "
                   "reads back correctly (GetCompCount 1, MediaOut1.Input wired "
                   "to the new tool, StyledText returning the value just set) — "
                   "but the rendered output is byte-for-byte the untouched source "
                   "media. Verified live on Studio 19.1.3.7 with the strongest "
                   "form of the test: MediaOut1 fed ONLY by a Text+, with no path "
                   "from MediaIn at all, still rendered the unmodified clip. "
                   "LoadFusionCompByName on the sole comp does not activate it "
                   "either. Contrast InsertFusionTitleIntoTimeline, whose comp "
                   "DOES render — text set via SetInput('StyledText') appears in "
                   "the output — so this is specific to comps attached to "
                   "media-backed clips, not to Fusion through the API generally.",
        "recommended": "For text or effects over picture, insert a Fusion title/"
                       "generator as its own timeline clip and set its Text+ "
                       "(fusion_comp set_text_plus), rather than attaching a comp "
                       "to the media clip. Note the destination track cannot be "
                       "chosen from the API (see the Track Selector entry), so "
                       "overlaying onto an existing clip's track is not currently "
                       "reachable end-to-end. Building the comp in the Fusion page "
                       "UI works; only the API-created comp is ignored.",
        "tags": ["fusion", "silent-failure", "render"],
        "submit": "bug",
    },
    {
        "symbol": "Composition.Paste",
        "object": "Fusion Composition",
        "reality": "Passing tool.SaveSettings()'s in-memory table to Paste() / "
                   "LoadSettings() fails across the Python bridge with an "
                   "OrderedDict/null-argument error and creates no node, while "
                   "reporting nothing useful.",
        "recommended": "Duplicate via AddTool(RegID) + SaveSettings(path)/"
                       "LoadSettings(path) through a temp .setting FILE, which "
                       "round-trips reliably. Identify the new node by name diff.",
        "tags": ["fusion", "bridge", "silent-failure"],
        "submit": "bug",
    },
    {
        "symbol": "FlowView.SetPos / FlowView.GetPosTable",
        "object": "Fusion FlowView (comp.CurrentFrame.FlowView)",
        "reality": "Node positions are read/written through the FlowView, not the "
                   "tool. SetPos returns nothing reliable; GetPosTable returns a "
                   "1-indexed table (or dict/tuple depending on bridge).",
        "recommended": "Use comp.CurrentFrame.FlowView.SetPos(tool, x, y); confirm "
                       "with GetPosTable and a liberal position parser.",
        "tags": ["fusion", "unreliable-return"],
        "submit": "bug",
    },
    {
        "symbol": "Timeline.GetTimelineByName",
        "object": "Project",
        "reality": "Does not exist. Timelines are looked up by index.",
        "recommended": "Iterate GetTimelineByIndex(1..GetTimelineCount()).",
        "tags": ["missing-method", "timeline"],
        "submit": "missing",
    },
    {
        "symbol": "Project render methods (AddRenderJob, SetRenderSettings, ...)",
        "object": "Project",
        "reality": "Render methods live on the Project object, not on a separate "
                   "render-settings interface.",
        "recommended": "Call proj.AddRenderJob(), proj.SetRenderSettings(), "
                       "proj.LoadRenderPreset() directly on the project.",
        "tags": ["render"],
    },
    {
        "symbol": "MediaPoolItem.GetClipProperty('Transcription')",
        "object": "MediaPoolItem",
        "reality": "Returns a PREVIEW of the transcription that ends in an "
                   "ellipsis when the full transcript is longer than the property "
                   "exposes.",
        "recommended": "Treat a trailing ellipsis as truncation (see "
                       "media_pool_item get_transcription's `truncated` flag).",
        "tags": ["transcription", "truncation"],
        "submit": "bug",
    },
    {
        "symbol": "ProjectManager.CreateProject (with a dirty Untitled project)",
        "object": "ProjectManager",
        "reality": "Returns None and pops a modal 'Save Current Project' dialog "
                   "when the current unsaved/Untitled project blocks the switch. "
                   "SaveProject() on an Untitled project re-triggers the same modal.",
        "recommended": "CloseProject(current) to discard the untitled project "
                       "without a prompt, then CreateProject; restore with "
                       "LoadProject afterward.",
        "tags": ["project", "modal", "silent-failure"],
        "submit": "bug",
    },
    {
        "symbol": "Timeline.InsertFusionCompositionIntoTimeline",
        "object": "Timeline",
        "reality": "Reliable way to obtain a Fusion comp on an otherwise empty "
                   "timeline: it inserts a Fusion composition clip whose comp is "
                   "then reachable via GetFusionCompByIndex(1).",
        "recommended": "Use it (rather than InsertGeneratorIntoTimeline) when you "
                       "need a comp to operate on.",
        "tags": ["fusion", "timeline"],
    },
    {
        "symbol": "Source Track Selector / destination track for Insert*IntoTimeline",
        "object": "Timeline",
        "reality": "There is no API to read or set the Source/Auto Track Selector "
                   "(the Edit-page patch panel that picks the destination track). "
                   "InsertTitleIntoTimeline, InsertFusionTitleIntoTimeline, "
                   "InsertGeneratorIntoTimeline, InsertFusionGeneratorIntoTimeline, "
                   "InsertOFXGeneratorIntoTimeline and "
                   "InsertFusionCompositionIntoTimeline take no trackIndex and "
                   "always drop the clip on the selector's current target (V1 in "
                   "practice). Locking lower video tracks does NOT redirect the "
                   "insert — verified live on 21.0.0: locking V1 makes the insert "
                   "FAIL rather than land on V2. Titles/generators also can't be "
                   "moved afterward (no MediaPoolItem, so AppendToTimeline clipInfo "
                   "and MoveClips don't apply).",
        "recommended": "Accept the limitation for titles/generators (insert lands "
                       "on V1). For clips that DO have a MediaPoolItem, target a "
                       "track with MediaPool.AppendToTimeline's clipInfo 'trackIndex' "
                       "instead (exposed as media_pool append_to_timeline clip_infos). "
                       "See issue #74.",
        "tags": ["missing-method", "timeline", "title", "generator", "track"],
        "submit": "missing",
        "issue": 74,
    },
    {
        "symbol": "Per-clip audio channel-format conversion (Stereo<->Mono)",
        "object": "MediaPoolItem / TimelineItem",
        "reality": "No scripting method converts an individual clip's audio "
                   "channel format. ConvertTimelineToStereo is timeline-wide, and "
                   "CreateStereoClip builds a 3D *visual* stereoscopic clip, not an "
                   "audio mono->stereo change. The Edit-page 'Clip Attributes > "
                   "Audio' channel mapping is UI-only.",
        "recommended": "Use the supported surface: timeline add_track with audioType "
                       "(create mono/stereo tracks), get_track_sub_type (query "
                       "format), convert_to_stereo (timeline-wide), and "
                       "timeline_item get_source_audio_channel_mapping. Per-clip "
                       "conversion is not possible. See issue #73.",
        "tags": ["missing-method", "audio", "channel"],
        "submit": "missing",
        "issue": 73,
    },
    {
        "symbol": "Native multicam clip creation",
        "object": "MediaPool",
        "reality": "There is no method to create a native multicam clip from a set "
                   "of angles. Angles can be stacked onto tracks programmatically, "
                   "but the multicam-clip conversion is a UI-only step.",
        "recommended": "Prepare a stacked timeline (media_pool setup_multicam_timeline) "
                       "and finish the multicam-clip conversion in the Resolve UI.",
        "tags": ["missing-method", "media-pool", "multicam"],
        "submit": "missing",
    },
    {
        "symbol": "Transition create / copy / clone",
        "object": "Timeline / TimelineItem",
        "reality": "The scripting API exposes no method to add, read, copy, or "
                   "clone an edit transition (cross-dissolve, etc.). Transitions "
                   "applied in the UI are invisible to and unmodifiable by scripts.",
        "recommended": "Apply/duplicate transitions in the Resolve UI; no scripted "
                       "equivalent exists.",
        "tags": ["missing-method", "timeline", "transition"],
        "submit": "missing",
    },
    {
        "symbol": "Cloud project enumeration / export / user management",
        "object": "ProjectManager",
        "reality": "Only CreateCloudProject, LoadCloudProject, ImportCloudProject "
                   "and RestoreCloudProject exist. There is no GetCloudProjectList "
                   "(list available cloud projects), no ExportToCloud, and no "
                   "Add/RemoveUserToCloudProject — so cloud collaboration can't be "
                   "fully automated.",
        "recommended": "Drive cloud project listing, export, and collaborator "
                       "management from the Resolve UI; only create/load/import/"
                       "restore are scriptable.",
        "tags": ["missing-method", "project", "cloud"],
        "submit": "missing",
    },
    {
        "symbol": "TimelineItem trim / move / re-time (no position setters)",
        "object": "TimelineItem",
        "reality": "TimelineItem exposes GetStart, GetEnd, GetDuration, "
                   "GetLeftOffset, GetRightOffset and GetSourceStart/EndFrame, but "
                   "NO matching setters. A clip cannot be trimmed, slipped, slid, "
                   "rolled, moved to another time/track, or have its duration "
                   "changed once it is on the timeline. Verified via dir() on "
                   "Resolve 21.0.0 (getters only).",
        "recommended": "Do edit-point adjustments in the Resolve UI, or rebuild the "
                       "timeline from MediaPool.AppendToTimeline clipInfos with the "
                       "desired startFrame/endFrame/recordFrame.",
        "tags": ["missing-method", "timeline", "edit", "trim"],
        "submit": "missing",
    },
    {
        "symbol": "Razor / blade / split a timeline item",
        "object": "Timeline / TimelineItem",
        "reality": "There is no method to split/cut/blade a clip at a given frame. "
                   "Verified absent on Timeline and TimelineItem (dir(), 21.0.0).",
        "recommended": "Split in the Resolve UI, or construct the cut up-front by "
                       "appending two clipInfos with the desired in/out points.",
        "tags": ["missing-method", "timeline", "edit"],
        "submit": "missing",
    },
    {
        "symbol": "Clip speed / retime ratio and speed ramps",
        "object": "TimelineItem",
        "reality": "SetProperty exposes only retime *quality* (RetimeProcess, "
                   "MotionEstimation) and transform/crop/composite/opacity keys — "
                   "not the speed value itself. There is no way to set a clip to a "
                   "given % speed, reverse it, or author a speed ramp. Verified "
                   "against the documented SetProperty key list AND by live "
                   "mutating attempt on 21.0.0: SetProperty('Speed'|'PlaybackSpeed'"
                   "|'RetimeSpeed'|'ClipSpeed', 50) all return False, while "
                   "SetProperty('RetimeProcess', 1) returns True.",
        "recommended": "Set clip speed/retime in the Resolve UI; no scripted "
                       "equivalent exists.",
        "tags": ["missing-method", "timeline", "retime", "speed"],
        "submit": "missing",
    },
    {
        "symbol": "Color node graph editing and primary grade values",
        "object": "Graph / TimelineItem",
        "reality": "The Graph object exposes node enable/label/count, LUT get/set, "
                   "cache mode, ResetAllGrades, ApplyGradeFromDRX and "
                   "ApplyArriCdlLut; TimelineItem adds SetCDL, CopyGrades and color "
                   "versions. But you cannot add, delete, or connect nodes, and you "
                   "cannot read or write primary grade values (lift/gamma/gain/"
                   "offset/contrast/curves/qualifiers/power windows). Grading is "
                   "limited to CDL, whole-grade DRX/LUT application and copying.",
        "recommended": "Build node trees and dial grades in the Resolve UI or via "
                       "DRX/CDL/LUT import; per-parameter grade control is not "
                       "scriptable.",
        "tags": ["missing-method", "color", "grade", "node"],
        "submit": "missing",
    },
    {
        "symbol": "Fairlight audio levels / pan / EQ / automation / FairlightFX",
        "object": "TimelineItem / Timeline",
        "reality": "There is no API to set clip or track volume, pan, EQ, audio "
                   "automation, or to add/configure FairlightFX. SetProperty covers "
                   "video transform only; the audio surface is read-only "
                   "(GetSourceAudioChannelMapping, GetAudioMapping, voice "
                   "isolation). Verified via dir() + SetProperty docs AND by live "
                   "mutating attempt on 21.0.0: SetProperty('Volume'|'Level'|'Gain'"
                   "|'AudioVolume', 0) all return False (note 'Pan' is the VIDEO "
                   "transform key, not audio pan, so it misleadingly succeeds).",
        "recommended": "Mix in the Fairlight UI; only voice-isolation state and "
                       "channel-mapping reads are scriptable.",
        "tags": ["missing-method", "audio", "fairlight"],
        "submit": "missing",
    },
    {
        "symbol": "Proxy / optimized-media generation",
        "object": "MediaPoolItem",
        "reality": "Only LinkProxyMedia, UnlinkProxyMedia and "
                   "LinkFullResolutionMedia exist (attach/detach EXISTING proxies). "
                   "There is no method to generate proxies or optimized media. "
                   "Verified via MediaPoolItem dir() (21.0.0).",
        "recommended": "Trigger proxy/optimized-media generation from the Resolve "
                       "UI; scripting can only link/unlink already-rendered proxies.",
        "tags": ["missing-method", "media-pool", "proxy"],
        "submit": "missing",
    },
    {
        "symbol": "Insert / Overwrite / Replace / Fit-to-Fill edit modes",
        "object": "MediaPool / Timeline",
        "reality": "MediaPool.AppendToTimeline (with optional recordFrame "
                   "positioning) is the only programmatic placement. The standard "
                   "edit modes — insert (ripple), overwrite, replace, fit-to-fill, "
                   "place-on-top — have no API. Verified via dir() (21.0.0).",
        "recommended": "Position clips with AppendToTimeline clipInfo recordFrame, "
                       "or perform insert/overwrite/replace edits in the Resolve UI.",
        "tags": ["missing-method", "timeline", "edit"],
        "submit": "missing",
    },
    {
        "symbol": "Render in Place / bake a timeline clip to new media",
        "object": "Timeline / TimelineItem / MediaPool",
        "reality": "There is no scripting method for the Edit-page clip "
                   "context-menu action 'Render in Place', which bakes a clip "
                   "(including its Fusion composition and effects) into a NEW "
                   "rendered media file and drops that file back on the timeline "
                   "at the same position, replacing the source clip. No "
                   "Render*/Bake*/Freeze* method exists on Timeline, TimelineItem "
                   "or MediaPool in the Resolve scripting API reference (BMD docs) "
                   "or a dir() audit. NOTE the frequently-confused-but-distinct "
                   "sibling: the render *cache* (a temporary, non-destructive "
                   "cache of a clip's Color/Fusion output that reduces playback "
                   "load WITHOUT creating a new media file) IS scriptable — "
                   "TimelineItem.SetColorOutputCache / SetFusionOutputCache "
                   "('Render Cache Color/Fusion Output' menu actions) and "
                   "Graph.SetNodeCacheMode. Render in Place is the permanent, "
                   "media-producing bake; the render cache is the transient one.",
        "recommended": "If the goal is only to reduce playback/render load, use "
                       "the render cache — exposed as timeline_item "
                       "get_color_cache/set_color_cache/get_fusion_cache/"
                       "set_fusion_cache and the Color-page graph node cache_mode "
                       "(no new media, fully reversible). If you genuinely need a "
                       "baked media file, render the clip's in/out range from the "
                       "Deliver page (proj.AddRenderJob with MarkIn/MarkOut) and "
                       "relink/append the result yourself, or run Render in Place "
                       "from the Resolve UI. There is no one-call API equivalent. "
                       "See issue #86.",
        "tags": ["missing-method", "timeline", "render", "cache", "render-in-place", "bake"],
        "submit": "missing",
        "issue": 86,
    },
    {
        "symbol": "Smart Bins / Power Bins creation",
        "object": "MediaPool",
        "reality": "Only AddSubFolder (a regular bin) exists. Smart Bins (rule-"
                   "based) and Power Bins (cross-project) cannot be created or "
                   "configured. Verified via MediaPool dir() (21.0.0).",
        "recommended": "Create Smart/Power Bins in the Resolve UI; only regular "
                       "bins are scriptable.",
        "tags": ["missing-method", "media-pool", "bins"],
        "submit": "missing",
    },
    {
        "symbol": "Per-subtitle text content and timing editing",
        "object": "TimelineItem (subtitle track)",
        "reality": "TimelineItem on a subtitle track exposes only 21 standard "
                   "transform/composite properties (Pan, Tilt, ZoomX, Opacity, "
                   "Crop, etc.). There are no methods to get or set subtitle "
                   "text (GetText/SetText), start time, end time, or duration "
                   "for individual subtitle items. Subtitles created via "
                   "CreateSubtitlesFromAudio or imported via the Resolve UI "
                   "cannot have their content or timing read or modified "
                   "programmatically. Verified via dir() and GetProperty() on "
                   "Resolve 21.0.0.48.",
        "recommended": "No workaround exists — subtitle text and timing are "
                       "completely inaccessible from the scripting API. Must "
                       "be edited in the Resolve UI.",
        "tags": ["missing-method", "subtitle", "text", "timing"],
        "submit": "missing",
    },
    {
        "symbol": "Subtitle track styling and presets",
        "object": "TimelineItem / Timeline / Project",
        "reality": "There is no API method to set or query subtitle font "
                   "family, font size, text color, background color, outline, "
                   "shadow, position, alignment, or to apply/query subtitle "
                   "style presets. TimelineItem.GetProperty() on subtitle "
                   "items returns only transform/composite keys. "
                   "Timeline.GetSetting() and Project.GetSetting() return "
                   "None for all probed subtitle-style keys (e.g. "
                   "'subtitleFontName', 'subtitleFontSize', "
                   "'subtitleTextColor', 'subtitleBackgroundColor', "
                   "'subtitlePosition', 'subtitleAlignment', "
                   "'subtitlePreset', 'subtitleStyle'). Verified via dir(), "
                   "GetProperty(), and GetSetting() on Resolve 21.0.0.48.",
        "recommended": "No workaround exists — subtitle styling is UI-only. "
                       "Burn-in overlays via Fusion titles are a visual "
                       "alternative but do not produce proper subtitle tracks.",
        "tags": ["missing-method", "subtitle", "style", "preset"],
        "submit": "missing",
    },
    {
        "symbol": "Speech recognition engine selection and SRT import",
        "object": "Timeline",
        "reality": "Timeline.CreateSubtitlesFromAudio(autoCaptionSettings) "
                   "always uses the built-in Resolve speech recognition "
                   "engine. There is no API parameter to select an alternative "
                   "provider (e.g. whisper-cli, Google Speech, AWS Transcribe). "
                   "The language selection via resolve.AUTO_CAPTION_LANGUAGE_* "
                   "is the only customization; the engine itself cannot be "
                   "changed. Furthermore, there is no API method to import an "
                   "SRT file into a subtitle track programmatically — "
                   "File -> Import -> Subtitle is UI-only.",
        "recommended": "No workaround exists for provider selection or SRT "
                       "import. External transcripts must be converted to SRT "
                       "and imported through the Resolve UI.",
        "tags": ["missing-method", "subtitle", "transcription",
                 "speech-recognition", "asr"],
        "submit": "missing",
    },
    {
        "symbol": "Media Pool folder rename",
        "object": "MediaPool",
        "reality": "MediaPool exposes AddSubFolder(name), "
                   "DeleteSubFolders([names]), and "
                   "MoveFolders([names], targetFolder) but no "
                   "RenameSubFolder(oldName, newName) method. Folders can be "
                   "created, deleted, and moved, but their names cannot be "
                   "changed through the API. Verified via dir() on Resolve "
                   "21.0.0.",
        "recommended": "Delete and recreate the folder with the desired name, "
                       "or rename in the Resolve UI.",
        "tags": ["missing-method", "media-pool", "folder"],
        "submit": "missing",
    },
    {
        "symbol": "hasattr() / getattr() on Resolve API objects (attribute fabrication)",
        "object": "(all Resolve scripting objects)",
        "reality": "The Python bridge returns a callable for ANY attribute name, so "
                   "hasattr(obj, 'TotallyMadeUpMethod') is always True and getattr "
                   "never raises. This makes capability detection by hasattr "
                   "impossible — verified on 21.0.0 (hasattr reported SetStart, "
                   "Razor, AddNode, GenerateProxy, AddSmartBin etc. as present "
                   "though none exist). Only dir() lists the real methods.",
        "recommended": "Never probe method existence with hasattr/getattr; test "
                       "membership against dir(obj) instead. Calling a fabricated "
                       "method typically returns None/False with no error.",
        "tags": ["bridge", "introspection", "silent-failure"],
        "submit": "bug",
    },
    {
        "symbol": "subprocess inheriting stdin under the MCP stdio server",
        "object": "(server runtime)",
        "reality": "A child process that inherits stdin can race-read bytes off "
                   "the JSON-RPC protocol stream and corrupt it; capture_output "
                   "redirects only stdout/stderr.",
        "recommended": "Pass stdin=subprocess.DEVNULL on every subprocess that can "
                       "run while serving over stdio.",
        "tags": ["runtime", "stdio", "subprocess"],
    },
    {
        "symbol": "MediaPoolItem.SetClipProperty('Reel Name', ...)",
        "object": "MediaPoolItem",
        "signature": "(propertyName, propertyValue) -> bool",
        "reality": "Setting the 'Reel Name' clip property returns True but the "
                   "value is silently dropped on read-back when the project is "
                   "configured to derive reel names automatically "
                   "(General Options > 'Assist using reel names from the:' set "
                   "to source clip file / embedding / filename pattern). The "
                   "same True-but-unpersisted behavior occurs via "
                   "SetMetadata('Reel Name', ...). Other clip properties on the "
                   "same clip (e.g. 'Comments') write and persist normally, so "
                   "this is field-specific, not a bridge/permission failure. "
                   "Verified on Resolve 21.0.0; reported as issue #77.",
        "recommended": "After writing 'Reel Name', read it back with "
                       "GetClipProperty('Reel Name') and refuse to report "
                       "success on mismatch; surface the project-setting gate to "
                       "the caller (server._verify_clip_property_writeback).",
        "tags": ["unreliable-return", "silent-failure", "metadata", "reel-name"],
        "submit": "bug",
        "issue": 77,
        "mitigation": ["_verify_clip_property_writeback", "_verify_writeback"],
    },
    {
        "symbol": "Graph.ApplyGradeFromDRX (node layout preserved on same-structure apply)",
        "object": "Graph",
        "signature": "(path, gradeMode) -> bool",
        "reality": "When the applied .drx has the same node structure/ids as the "
                   "target's current graph, Resolve matches nodes and KEEPS the "
                   "existing node-editor x/y layout — the .drx's stored node "
                   "positions are silently ignored (returns True). Positions from "
                   "the .drx are only honored when the target graph differs "
                   "structurally (e.g. after ResetAllGrades, or a different node "
                   "count/ids). Verified on Resolve 19.1.3: applying a "
                   "positions-only-modified copy of a clip's own grade back to it "
                   "is a layout no-op.",
        "recommended": "To programmatically re-layout a clip's node graph "
                       "(Cleanup Node Graph has no API), reset the grade first, "
                       "then apply the re-positioned .drx: grab still → rewrite "
                       "node x/y → ResetAllGrades → ApplyGradeFromDRX. Grade "
                       "values round-trip byte-identically via the lossless Body "
                       "pass-through.",
        "tags": ["silent-failure", "color", "node-graph", "layout", "drx"],
    },
    {
        "symbol": "MediaPool.AppendToTimeline clipInfo endFrame (exclusive bound)",
        "object": "MediaPool",
        "signature": "([{mediaPoolItem, startFrame, endFrame, recordFrame, "
                     "trackIndex, mediaType}]) -> [TimelineItem]",
        "reality": "clipInfo endFrame is an EXCLUSIVE bound: the appended item's "
                   "duration is endFrame - startFrame frames, not "
                   "endFrame - startFrame + 1. Verified by readback probe on "
                   "Resolve Studio 21.0 — appending {startFrame: 6254, "
                   "endFrame: 6348} yields a 94-frame item, and 130 such "
                   "appends whose absolute recordFrames advance by exactly "
                   "(endFrame - startFrame) assemble a gap-free track whose "
                   "total length equals the sum of (end - start). Code that "
                   "assumes an inclusive bound drifts one frame per clip: "
                   "advancing a record cursor by (end - start + 1) leaves a "
                   "1-frame hole between consecutive clips, and converting a "
                   "half-open range with (end - 1) shaves the range's last "
                   "frame.",
        "recommended": "Treat [startFrame, endFrame) as half-open everywhere: "
                       "duration = endFrame - startFrame; next recordFrame = "
                       "previous recordFrame + duration; no ±1 corrections "
                       "when mirroring keep-ranges into clipInfos.",
        "tags": ["timeline", "edit", "off-by-one", "readback"],
    },
    {
        "symbol": "Graph.SetLUT (master-LUT-dir-only resolution)",
        "object": "Graph",
        "signature": "(nodeIndex, lutPath) -> bool",
        "reality": "SetLUT resolves lutPath ONLY against the master (system) LUT "
                   "directory and its configured custom LUT paths -- NOT the "
                   "per-user LUT dir that the dctl tool / Project LUT install "
                   "writes to. A bare basename in the user dir returns False, and "
                   "so does an ABSOLUTE path pointing into the user dir; "
                   "RefreshLUTList() does not change this. A subfolder-relative "
                   "path under the master root (e.g. 'MCP/Foo.cube') DOES resolve. "
                   "Net effect: a LUT/DCTL the dctl tool just installed can never "
                   "be applied by SetLUT as-is, so set_lut used to always return "
                   "{success: false}. Verified live on Studio 19.1.3.7 (basename "
                   "and absolute user-dir path both False, before and after "
                   "RefreshLUTList; master-dir and master-subfolder paths True); "
                   "the originating report (PR #90) observed the same on 21.0.2, "
                   "so it is not version-specific.",
        "recommended": "On a False return, locate the LUT, copy it into a "
                       "namespaced subfolder of the master LUT dir (MCP/, so it "
                       "does not clobber stock LUTs by basename), call "
                       "RefreshLUTList(), and retry with the master-relative path. "
                       "graph.set_lut and the granular graph_set_lut now do this "
                       "automatically via src.utils.lut_paths.ensure_lut_in_master.",
        "tags": ["color", "lut", "path-resolution", "silent-failure"],
        "submit": "bug",
        "issue": 90,
        "mitigation": ["_ensure_lut_in_master"],
    },
    {
        "symbol": "Project.GetRenderCodecs",
        "object": "Project",
        "signature": "(renderFormat) -> {codec description: codec name}",
        "reality": "Returns {description: id} — the human-readable description is "
                   "the KEY and the id Resolve actually accepts is the VALUE. "
                   "SetCurrentRenderFormatAndCodec, GetRenderCodecs and "
                   "GetRenderResolutions all require the id, so passing the "
                   "description a user sees in the Deliver page is rejected. "
                   "Verified live on Studio 19.1.3.7: ('mov', 'Apple ProRes 422 "
                   "HQ') -> False while ('mov', 'ProRes422HQ') -> True, and "
                   "('mp4', 'H.264') -> False while ('mp4', 'H264') -> True. It "
                   "affects every family, not only the ones whose id differs "
                   "obviously. Mirrors the same trap in GetRenderFormats, which "
                   "returns {format: extension}.",
        "recommended": "Normalize both arguments through the live maps before "
                       "calling: src.utils.render_ids.render_format_id_from_formats "
                       "and render_codec_id_from_codecs accept a description or an "
                       "id and return the id.",
        "tags": ["render", "deliver", "silent-failure", "id-vs-label"],
        "submit": "bug",
        "issue": 59,
        "mitigation": ["_render_format_id", "_render_codec_id"],
    },
    {
        "symbol": "Project.SetCurrentRenderFormatAndCodec",
        "object": "Project",
        "signature": "(format, codec) -> bool",
        "reality": "Some render formats expose NO codecs at all — "
                   "GetRenderCodecs('wav') and GetRenderCodecs('gif') both return "
                   "{} on Studio 19.1.3.7 — and the call then rejects every codec "
                   "value, including the empty string, the format id itself, and "
                   "any plausible name ('Linear PCM'). There is no documented way "
                   "to select such a format through this API, so an audio-only WAV "
                   "deliverable is not expressible in scripting.",
        "recommended": "Check GetRenderCodecs(format) first; when it is empty, "
                       "treat the format as unreachable through this API rather "
                       "than guessing a codec value. Render audio-only via "
                       "ExportVideo=False on a format that does expose codecs, or "
                       "drive it from a saved render preset.",
        "tags": ["render", "deliver", "audio", "unsupported"],
        "submit": "missing",
    },
    {
        "symbol": "ProjectManager.SaveProject",
        "object": "ProjectManager",
        "signature": "() -> bool",
        "reality": "On the default, never-saved project named 'Untitled Project' "
                   "this call CANNOT succeed — the project has no location and "
                   "there is no SaveProjectAs to give it one — and the two modes "
                   "fail differently. In the GUI it returns False. HEADLESS IT "
                   "BLOCKS FOREVER: measured on a cold -nogui boot with the "
                   "database verified attached immediately beforehand, no return "
                   "after 45s, the client parked in Fusion::RemoteApp::WaitPkt. "
                   "Resolve wants a Save-As dialog and waits for an answer that "
                   "cannot arrive. It also degrades the instance: after the hung "
                   "call was interrupted, SaveProject began returning None "
                   "instantly on that instance. On a named project it is fine in "
                   "both modes.",
        "recommended": "Guard it: only call SaveProject when "
                       "GetCurrentProject().GetName() != 'Untitled Project'. "
                       "There is nothing to save on the default project and the "
                       "call cannot succeed, so skipping it loses nothing. Do NOT "
                       "reach for headless to dodge the GUI's save dialog — "
                       "headless turns that dialog into an unbounded hang that no "
                       "human can clear.",
        "tags": ["project", "modal", "headless", "hang", "silent-failure", "unreliable-return"],
        "submit": "bug",
        "mitigation": ["save_project_if_safe"],
    },
    {
        "symbol": "Resolve.GetCurrentPage",
        "object": "Resolve",
        "signature": "() -> string",
        "reality": "A headless (-nogui) instance answers with a real page name, "
                   "not None, and OpenPage() succeeds and reads back for all "
                   "seven pages with no UI present. Nothing on the scripting API "
                   "distinguishes a headless Resolve from one with a window — "
                   "product name, version, layout presets, Gallery handles and "
                   "Fusion comps all behave identically (Studio 19.1.3.7, 238 "
                   "paired observations, zero headless-only failures).",
        "recommended": "Do not infer headlessness from any API reading. Use "
                       "resolve_control runtime_mode, which reads -nogui out of "
                       "the process argv — the only place it is visible.",
        "tags": ["headless", "page", "detection"],
        "mitigation": ["runtime_mode", "resolve_runtime.is_headless"],
    },
    {
        "symbol": "GalleryStillAlbum.ExportStills",
        "object": "GalleryStillAlbum",
        "signature": "(galleryStills, folderPath, filePrefix, format) -> bool",
        "reality": "PANEL-dependent, not mode-dependent — and the distinction "
                   "took three revisions of this entry to pin down, so the "
                   "evidence is recorded rather than summarised. Across four "
                   "controlled 92-probe sweeps (2 GUI, 2 headless, 2026-08-01) it "
                   "returned False and wrote nothing in ALL FOUR, while "
                   "Timeline.GrabStill() succeeded in all four — so it is not "
                   "being handed an empty still. In one earlier GUI session it "
                   "DID work, returning True and writing 2 files. The variable "
                   "that differed is not the mode: it is whether the Gallery "
                   "panel was visible on the Color page, which depends on the "
                   "restored workspace layout and which the harness does not "
                   "control. A headless session can never satisfy it, so in "
                   "practice the call never works headless; a GUI session "
                   "satisfies it only sometimes. "
                   "Project.ExportCurrentFrameAsStill worked in all four runs in "
                   "both modes.",
        "recommended": "Do not use ExportStills unattended in either mode — a "
                       "GUI session is not sufficient, only a GUI session with "
                       "the Gallery panel open. Use "
                       "Project.ExportCurrentFrameAsStill for pixels (verified in "
                       "both modes, four for four) or drp.extract_node_graphs for "
                       "grades. If ExportStills must be used, have the user open "
                       "Workspace > Gallery first and verify the written files "
                       "rather than trusting the return.",
        "tags": ["gallery", "stills", "headless", "unreliable-return"],
        "submit": "bug",
    },
]


def lookup_api_truth(query: Optional[str] = None) -> List[Dict[str, Any]]:
    """Return verified facts matching `query`, or all facts if no query.

    Matches a case-insensitive substring against the symbol, tags, and reality.
    """
    if not query:
        return list(API_TRUTH)
    q = query.lower()
    out = []
    for e in API_TRUTH:
        hay = " ".join([
            e.get("symbol", ""),
            e.get("object", ""),
            e.get("reality", ""),
            " ".join(e.get("tags", [])),
        ]).lower()
        if q in hay:
            out.append(e)
    return out


def submittable_limitations() -> Dict[str, List[Dict[str, Any]]]:
    """Group ``submit``-tagged entries for the Blackmagic-facing report.

    Returns ``{"missing": [...], "bug": [...]}`` — entries Blackmagic should add
    vs. behaviors they should fix — preserving API_TRUTH order within each group.
    """
    groups: Dict[str, List[Dict[str, Any]]] = {"missing": [], "bug": []}
    for e in API_TRUTH:
        kind = e.get("submit")
        if kind in groups:
            groups[kind].append(e)
    return groups
